language: python

python:
    - 2.7

install:
    - pip install pyyaml --use-mirrors # Required by the installer
    - sudo apt-get install --yes git libz-dev unzip libssl-dev
    - wget https://raw.github.com/chapmanb/bcbio-nextgen/master/scripts/bcbio_nextgen_install.py
    - python bcbio_nextgen_install.py /usr/local/share/bcbio-nextgen --tooldir=/usr/local  --distribution ubuntu --nodata

notifications:
    email: false

before_script:
    - cd tests
    #Export some environment variables
    - export PICARD_HOME=/usr/share/java/picard
    - export SNPEFF_HOME=/usr/share/java/snpeff
    - export GATK_HOME=/usr/share/java/gatk

script: nosetests -s -v --with-xunit -a standard
