sudo: required
dist: trusty
language: generic

env:
  global:
    - secure: "VJSdyR3BUpDGf7ot0I+GvSVR77TaMgxgscW1pFgxeitr3XvZ9la+PMuSqKH1B1TR/8Gq+l507FnQb1I/zjzUOvomX2gnsL6CcbTml8DKUz12kmQ0ixGT5IxZjDuBDvJwOJlRg1JLgJkcxMHa9EEmDZTh7Feyu7jJC9qeGKSyjFw="
  matrix:
    - BCBIO_DOCKER_PRIVILEGED=True ARVADOS_API_HOST=qr1hi.arvadosapi.com

before_install:
  # Fix issue with boto2 and gce https://github.com/travis-ci/travis-ci/issues/7940#issuecomment-311046316
  - export BOTO_CONFIG=/dev/null
  # Temporal fix for networking problem: https://github.com/travis-ci/travis-ci/issues/1484
  - echo "127.0.1.1 "`hostname` | sudo tee /etc/hosts
  # Get and install anaconda for custom Python installation
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  - bash Miniconda3-latest-Linux-x86_64.sh -b -p ~/install/bcbio-vm/anaconda

install:
  # Install bcbio-nextgen and bcbio-nextgen-vm
  - df -h
  - export PATH=~/install/bcbio-vm/anaconda/bin:$PATH
  - conda install --yes nomkl
  - conda install --yes -c conda-forge -c bioconda bcbio-nextgen python=3
  - conda install --yes -c conda-forge -c bioconda bcbio-nextgen-vm python=3
  # Clean up space with external tools we don't need for tests
  - conda clean --yes --tarballs --index-cache
  - conda remove --yes --force qt
  - rm -rf ~/install/bcbio-vm/anaconda/pkgs/qt-*
  - du -sch ~/install/bcbio-vm/anaconda/pkgs/* | sort -h
  - df -h
  # Update to latest bcbio-nextgen code externally
  - rm -rf ~/install/bcbio-vm/anaconda/lib/python*/site-packages/bcbio
  - rm -rf ~/install/bcbio-vm/anaconda/lib/python*/site-packages/bcbio_nextgen-*
  - ~/install/bcbio-vm/anaconda/bin/python setup.py install

jobs:
  include:
    - stage: test
      name: "Variant standard"
      script:
        # -- Prepare variant docker image
        - docker pull quay.io/bcbio/bcbio-vc
        - docker images
        - df -h
        # Update to latest bcbio-nextgen code within the container
        - bcbio_vm.py devel setup_install -i quay.io/bcbio/bcbio-vc
        # -- Standard bcbio variant tests
        - docker run -v `pwd`:`pwd` quay.io/bcbio/bcbio-vc bash -c "cd `pwd` && /usr/local/share/bcbio-nextgen/anaconda/bin/py.test -p no:cacheprovider -p no:stepwise tests/unit --cov=bcbio"
        - py.test -p no:cacheprovider -p no:stepwise tests/bcbio_vm -v -m docker_multicore
        # XXX Arvados tests failing with 404 when contacting from Travis
        # - sudo mkdir -p /etc/pki/tls/certs && sudo ln -s /etc/ssl/certs/ca-certificates.crt /etc/pki/tls/certs/ca-bundle.crt
        # - py.test -p no:cacheprovider -p no:stepwise tests/bcbio_vm -v -s -m cwl_arvados
    - stage: test
      name: "Variant CWL"
      script:
        - docker pull quay.io/bcbio/bcbio-vc
        - docker images
        - df -h
        # Update to latest bcbio-nextgen code within the container
        - bcbio_vm.py devel setup_install -i quay.io/bcbio/bcbio-vc
        # XXX Currently commented out joint test, taking too long and causing Travis timeouts
        # - py.test -p no:cacheprovider -p no:stepwise tests/bcbio_vm -v -s -m cwl_docker_joint
        - py.test -p no:cacheprovider -p no:stepwise tests/bcbio_vm -v -s -m cwl_docker_somatic
        # -- Cleanup variant docker image
        - docker ps -a -q | xargs --no-run-if-empty docker rm
        - docker rmi -f quay.io/bcbio/bcbio-vc
        - docker images | grep '<none>' | awk '{print $3}' | xargs --no-run-if-empty docker rmi
        - docker images
    - stage: test
      name: "RNA-seq CWL"
      script:
        - docker pull quay.io/bcbio/bcbio-rnaseq
        - docker images
        - df -h
        - bcbio_vm.py devel setup_install -i quay.io/bcbio/bcbio-rnaseq
        - py.test -p no:cacheprovider -p no:stepwise tests/bcbio_vm -v -s -m cwl_docker_rnaseq
        # -- Cleanup RNA-seq docker image
        - docker ps -a -q | xargs --no-run-if-empty docker rm
        - docker rmi -f quay.io/bcbio/bcbio-rnaseq
        - docker images | grep '<none>' | awk '{print $3}' | xargs --no-run-if-empty docker rmi
        - docker images

after_failure:
  - df -h

notifications:
  email: false
  slack:
    secure: iMn3Iih7cVmWci7A/Rpozc9Fn5IDKr3o6Y7XAWHEBiOEFlBwkC3oHFZxTC1+wZQiDNR87yVF9z3+FhYTYizpUeCPMddfNLMzdcO0EGtpckZOzX7aaFjqQCWhtucDnDQYaHhZIPKATrWvpPSYm7bpyp/p9cqgE/a9uvFLRMrIyzM=
