version: 5

aliases:
  human: true
  snpeff: GRCh38.78
  ensembl: homo_sapiens_vep_79_GRCh38

variation:
  dbsnp: ../variation/dbsnp-144.vcf.gz
  train_hapmap: ../variation/hapmap_3.3.vcf.gz
  train_omni: ../variation/1000G_omni2.5.vcf.gz
  train_1000g: ../variation/1000G_phase1.snps.high_confidence.vcf.gz
  train_indels: ../variation/Mills_and_1000G_gold_standard.indels.vcf.gz
  lcr: ../variation/LCR.bed.gz
