version: 7

aliases:
  human: true
  snpeff: GRCh38.78
  ensembl: homo_sapiens_vep_81_GRCh38

variation:
  dbsnp: ../variation/dbsnp-144.vcf.gz
  train_hapmap: ../variation/hapmap_3.3.vcf.gz
  train_omni: ../variation/1000G_omni2.5.vcf.gz
  train_1000g: ../variation/1000G_phase1.snps.high_confidence.vcf.gz
  train_indels: ../variation/Mills_and_1000G_gold_standard.indels.vcf.gz
  lcr: ../coverage/problem_regions/repeats/LCR.bed.gz
  sv_repeat: ../coverage/problem_regions/repeats/sv_repeat_telomere_centromere.bed

rnaseq:
  transcripts: ../rnaseq/ref-transcripts.gtf
  transcripts_mask: ../rnaseq/ref-transcripts-mask.gtf
  transcriptome_index:
    tophat: ../rnaseq/tophat/hg19_transcriptome.ver
  dexseq: ../rnaseq/ref-transcripts.dexseq.gff3
  refflat: ../rnaseq/ref-transcripts.refFlat
  rRNA_fa: ../rnaseq/rRNA.fa
