galaxy_url: http://your/galaxy/url
galaxy_api_key: your_galaxy_api_key
galaxy_config: /opt/source/galaxy/web/universe_wsgi.ini
program:
  bowtie: bowtie
  samtools: samtools
  bwa: bwa
  maq: maq
  ucsc_bigwig: wigToBigWig
  picard: /source/Picard
  snpEff: /source/share/snpEff
  fastx_stats: fastx_quality_stats
  fastx_graph: fastq_quality_boxplot_graph.sh
  pdflatex: pdflatex
  ps2pdf: ps2pdf
  solexaqa: SolexaQA.pl
  barcode: barcode_sort_trim.py
algorithm:
  aligner: bowtie
  max_errors: 2
  num_cores: 8
  stringency: high
  platform: illumina
  recalibrate: false
  snpcall: false
  bc_mismatch: 2
  bc_read: 1
  bc_position: 3

log_dir: /array0/projects/Sequencing/log
msg_process_tag: sqn_finished_process
msg_store_tag: sqn_finished_store
store_dir: /mad/store/clients/cscshared/solexadata
store_user: cscshared
store_host: bricklayer01.partners.org

analysis:
  # Can specify a remote server to copy analysis files and run
  # the analysis programs on. This needs a configuration file 
  # like this with program information for the remote machine.
  # The default is to run the analysis on the local machine.
  user:
  host:
  login_shell:
  config_file:
  store_dir: /store4/solexadata
  base_dir: /array0/projects/Sequencing
  towig_script: bam_to_wiggle.py
  process_program: automated_initial_analysis.py
  upload_program: upload_to_galaxy.py
# configuration algorithm changes for custom post-processing steps
custom_algorithms:
  'Broad SNP':
    ref_ext: '-broad'
    aligner: maq
    recalibrate: true
    snpcall: true
    dbsnp: snps/snp130.vcf
    hybrid_bait: bait_list
    hybrid_target: target_list
  'SNP calling':
    aligner: bwa
    recalibrate: true
    snpcall: true
    dbsnp: snps/snp130.vcf
