galaxy_config: universe_wsgi.ini
dump_directories:
  - /array10
  - /array11
  - /array12
log_dir: /home/chapman/transfer/log
# Notifications from the logging system via email
#email: ngs_admin@example.com
# Optional directory to do post-processing analysis. 
# Needed if doing processing on the same machine as output.
postprocess_dir: 
# Optional directories to look for Illumina samplesheets.
# Needed if using these samplesheets for specifying run contents.
samplesheet_directories:
  - /path/to/csv/samplesheets/dir
# Pointer to a plain text file which will be used to keep track of 
# directories that have already been transferred.
msg_db: /home/chapman/transfer/transferred.db
program:
  olb: /home/chapman/install/OLB-1.8/OLB-1.8.0
  olb_make: make
algorithm:
  num_cores: 8
distributed:
  rabbitmq_vhost: bionextgen
