# Configuration comparing alignment methods, preparation approaches
# and variant callers for an NA12878 exome dataset from EdgeBio.
#
# See the bcbio-nextgen documentation for full instructions to
# run this analysis:
# https://bcbio-nextgen.readthedocs.org/en/latest/contents/testing.html#example-pipelines
---
upload:
  dir: ../final
details:
  - files: [../input/NA12878-NGv3-LAB1360-A_1.fastq.gz, ../input/NA12878-NGv3-LAB1360-A_2.fastq.gz]
    description: NA12878-1
    metadata:
      sex: female
    analysis: variant2
    genome_build: GRCh37
    algorithm:
      aligner: bwa
      align_split_size: 5000000
      variantcaller: [freebayes, gatk-haplotype, samtools]
      recalibrate: gatk
      realign: gatk
      merge_bamprep: true
      validate: ../input/GiaB_v2_19.vcf.gz
      validate_regions: ../input/GiaB_v2_19_regions.bed
      variant_regions: ../input/NGv3.bed
      ensemble:
        numpass: 2
  - files: [../input/NA12878-NGv3-LAB1360-A_1.fastq.gz, ../input/NA12878-NGv3-LAB1360-A_2.fastq.gz]
    description: NA12878-2
    metadata:
      sex: female
    analysis: variant2
    genome_build: GRCh37
    algorithm:
      aligner: bwa
      align_split_size: 5000000
      mark_duplicates: true
      recalibrate: false
      realign: false
      variantcaller: [freebayes, gatk-haplotype, samtools]
      merge_bamprep: false
      validate: ../input/GiaB_v2_19.vcf.gz
      validate_regions: ../input/GiaB_v2_19_regions.bed
      variant_regions: ../input/NGv3.bed
      ensemble:
        numpass: 2
