# Example configuration for running a whole genome variant calling
# pipeline on public NA12878 data from Illumina's Platinum Genome project
# http://www.illumina.com/platinumgenomes/
#
# For a quick-start guide to running this analysis, see the example
# pipeline section of the documentation:
# https://bcbio-nextgen.readthedocs.org/en/latest/contents/testing.html#example-pipelines
---
upload:
  dir: ../final
fc_date: '130327'
fc_name: iplat
details:
  - algorithm:
      aligner: bwa
      variantcaller: gatk
      quality_format: Standard
      coverage_interval: genome
      validate: ../input/NISTIntegratedCalls_13datasets_130719_allcall_UGHapMerge_HetHomVarPASS_VQSRv2.17_all_nouncert_excludesimplerep_excludesegdups_excludedecoy_excludeRepSeqSTRs_noCNVs.vcf
      validate_regions: ../input/union13callableMQonlymerged_addcert_nouncert_excludesimplerep_excludesegdups_excludedecoy_excludeRepSeqSTRs_noCNVs_v2.17.bed
    analysis: variant2
    description: NA12878
    genome_build: GRCh37
    metadata:
      sex: female
    lane: 1
    files: [../input/ERR091571_1.fastq.gz, ../input/ERR091571_2.fastq.gz]
