# Configuration comparing alignment methods, preparation approaches
# and variant callers for an NA12878 exome dataset from EdgeBio.
#
# See the bcbio-nextgen documentation for full instructions to
# run this analysis:
# https://bcbio-nextgen.readthedocs.org/en/latest/contents/testing.html#example-pipelines
---
upload:
  dir: ../final
fc_date: '2013-09-03'
fc_name: methodcmp
details:
  - files: [../input/NA12878-NGv3-LAB1360-A_1.fastq.gz, ../input/NA12878-NGv3-LAB1360-A_2.fastq.gz]
    description: NA12878-1
    analysis: variant2
    genome_build: GRCh37
    algorithm:
      aligner: bwa
      align_split_size: 5000000
      variantcaller: [gatk, freebayes, gatk-haplotype]
      quality_format: Standard
      coverage_interval: regional
      merge_bamprep: true
      validate: ../input/NIST_IntegratedCalls_12datasets_130517_HetHomVarPASS_VQSRv2.15.vcf
      validate_regions: ../input/union12callableMQonlymerged_addcert_nouncert_excludesegdups_excludedecoy_noCNVs_v2.15b.bed
      variant_regions: ../input/NGv3.bed
      ensemble:
        format-filters: [DP < 4]
        classifiers: 
          balance: [AD, FS, Entropy]
          calling: [ReadPosEndDist, PL, PLratio, Entropy, NBQ]
        classifier-params:
          type: svm
        trusted-pct: 0.65
