# Template for human RNA-seq using Illumina prepared samples
---
details:
  - analysis: RNA-seq
    genome_build: GRCh37
    algorithm:
      quality_format: Standard
      aligner: tophat2
      trim_reads: read_through
      adapters: [truseq, polya]
      strandedness: unstranded
upload:
  dir: ../final
