upload:
  dir: ../final
details:
  - analysis: smallRNA-seq
    algorithm:
      aligner: star # any other aligner is supported.
      # change adapter according project
      adapters: ["TGGAATTCTCGGGTGC"] 
      expression_caller: [trna, seqcluster, mirdeep2]
      # expression_caller: [trna, seqcluster, mirdeep2, mirge] Read docs to know how to use
      # miRge tools: https://bcbio-nextgen.readthedocs.io/en/latest/contents/pipelines.html#smallrna-seq
      species: hsa
    genome_build: hg19
#resources:
#  atropos: 
#    options: ["-u 4", "-u -4"]
#  mirge: 
#    options: ["-lib $PATH_TO_LIBS_FOLDER"]  