# Template for variant calling from pre-aligned input BAM files.
# Fixes read group information to that specified in the input and
# ensures sorting to match the reference genome.
# Uses freebayes calling without GATK post-alignment BAM pre-processing
# (recalibration and realignment)
---
details:
  - analysis: variant2
    genome_build: GRCh37
    # to do multi-sample variant calling, assign samples the same metadata / batch
    # metadata:
    #   batch: your-arbitrary-batch-name
    algorithm:
      aligner: false
      bam_clean: picard
      bam_sort: coordinate
      mark_duplicates: samtools
      recalibrate: false
      realign: false
      variantcaller: freebayes
      platform: illumina
      quality_format: Standard
      coverage_interval: genome
      # for targetted projects, set the region
      # variant_regions: /path/to/your.bed
