# Template for paired (tumor/normal) variant calling
---
details:
  - analysis: variant2
    genome_build: GRCh37
    # In order to do paired variant calling, samples should belong to the
    # same batch ("batch" under "metadata" below") and have a "phenotype"
    # field stating either "normal" or "tumor". For each batch there
    # should be a sample with "tumor" phenotype and a sample with "normal"
    # phenotype (no more than two samples per batch)
    metadata:
       batch: your-batch-name
       phenotype: tumor # or "normal"
    algorithm:
      aligner: bwa
      variantcaller: [vardict, mutect2, strelka2]
      ensemble:
        numpass: 2
      # for targetted projects, set the region
      # variant_regions: /path/to/your.bed
